name: Build template

on:
  push:
    branches:
      - master
  pull_request:
  registry_package:

jobs:
  build-template:
    name: Build template
    runs-on: ubuntu-latest
    container:
      image: thomasweise/docker-texlive-full:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build pdf
        run: |
          for style in casual classic banking oldstyle fancy contemporary
          do
            echo "Compiling style $style..."
            latexmk -c
            sed -i "s/moderncvstyle[]{contemporary}/\moderncvstyle[]{${style}}/g" template.tex
            latexmk -pdflua ./template.tex
            mv template.pdf template_${style}.pdf
            mv template.log template_${style}.log
          done

      - name: Upload pdf
        uses: actions/upload-artifact@v4
        with:
          name: template.pdf
          path: ./template_*.pdf

      - name: Upload log
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: template.log
          path: ./template_*.log
